included:
  - MyTravelHelper
  - MyTravelHelperTests
excluded:
  - XMLParsing
  - DropDown
  - SwiftSpinner
  - SwiftLint
disabled_rules:
  - todo
cyclomatic_complexity: 
    ignores_case_statements: true
    warning: 10
    error: 10
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - explicit_init
  # This rule is giving false positives with Xcode 11.6
  # See https://github.com/realm/SwiftLint/issues/3150
  #- extension_access_modifier
  - fatal_error_message
  - file_name
  - first_where
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - force_unwrapping

trailing_semicolon: error
force_unwrapping: error
first_where: error
opening_brace: error
closure_spacing: error
closure_end_indentation: error
file_name: error
function_parameter_count:
  warning: 5
  error: 5
identifier_name:
  excluded:
    - id
line_length: 
  warning: 160
  error: 160
function_body_length: 
  warning: 50
  error: 52
type_body_length:
  warning: 200
  error: 200
number_separator:
  minimum_length: 5
file_name:
  excluded:
    - main.swift
file_length:
  warning: 500
  error: 500
custom_rules:
  rule_id:
    included: Source/SwiftLintFramework/Rules/\w+\.swift
    name: Rule ID
    message: Rule IDs must be all lowercase, snake case and not end with `rule`
    regex: identifier:\s*("\w+_rule"|"\S*[^a-z_]\S*")
    severity: error
  rule_test_function:
    included: Tests/SwiftLintFrameworkTests/RulesTests.swift
    name: Rule Test Function
    message: Rule Test Function mustn't end with `rule`
    regex: func\s*test\w+(r|R)ule\(\)
    severity: error
  empty_line_after_function_closing_bracket:
    name: "Empty line before function"
    message: "Add empty line before function" 
    regex: '\}\n *func'
    severity: warning
